---
title: "RMaiorQuePython"
author: "TIME R"
date: "4/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

```{r}

library(tidyverse)
baby_shark <- readr::read_csv("Fish.csv") %>%
  janitor::clean_names()
```

```{r}
baby_shark %>%
  count(species) %>%
  mutate(species = fct_reorder(species, n)) %>%
  ggplot(aes(n, species, fill = species)) +
  geom_col() +
  theme_minimal() +
  labs(title = "Os 7 maiores peixes do mundo", fill = "Espécies",
       x = "Quantidade", y = "Espécies")
```

```{r}
baby_shark %>%
  ggplot(aes(weight, height)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Relação entre peso e altura",
       x = "Peso", y = "Altura")
```

```{r}
baby_shark %>%
  ggplot(aes(width, height, size = weight)) +
  geom_point() +
  theme_minimal() +
  labs(title = "Relação entre largura, altura e peso",
       x = "Largura", y = "Altura", size = "Peso")
```

```{r}
baby_shark %>%
  ggplot(aes(height)) +
  geom_histogram() +
  theme_minimal() +
  labs(title = "Distribuição da altura dos baby sharks",
       x = "Altura", y = "Frequencia")
```

```{r}
lm(height + width ~ weight, data = baby_shark)
```


